# Generated by Django 3.2.1 on 2022-01-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0006_round2database_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2database',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AlterField(
            model_name='round2database',
            name='interviewer',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='round2database',
            name='number',
            field=models.CharField(default='Null', max_length=14),
        ),
        migrations.AlterField(
            model_name='round2database',
            name='selected',
            field=models.CharField(blank=True, default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='round2database',
            name='slot',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='round2database',
            name='taken',
            field=models.CharField(blank=True, default='No', max_length=10),
        ),
    ]
