# Generated by Django 3.2.1 on 2022-01-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0007_remove_database_interviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='file',
            field=models.CharField(blank=True, default=False, max_length=5000),
        ),
    ]
