# Generated by Django 3.2.1 on 2022-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0008_alter_database_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='file',
            field=models.URLField(),
        ),
    ]
